package Vistas;

import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyectoprogramacion2.OrdenCompra;
import proyectoprogramacion2.Producto;
import proyectoprogramacion2.Sistema;

/**
 *
 * @author kate
 */
public class entradaMercaderia extends javax.swing.JFrame {
    Sistema sis;
    ArrayList<Producto> productos = new ArrayList();
    private OrdenCompra ordComp;

    /**
     * Creates new form entradaMercaderia
     */
    public entradaMercaderia() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Entrada Mercadería");
        sis = new Sistema();
    }

    public void realizarCompra() {
        /*
         orden de compra 
         cedula juridica
         */

    }

    public void mostrarCompra() {
        
    }

    public void ocultarCompra() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radOrdenCompra = new javax.swing.JRadioButton();
        radDevolucion = new javax.swing.JRadioButton();
        jLCliente = new javax.swing.JLabel();
        jLFactura = new javax.swing.JLabel();
        jLMotivo = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        btnIncorporar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ENTRADA DE MERCADERIA");

        buttonGroup1.add(radOrdenCompra);
        radOrdenCompra.setText("Orden de Compra");
        radOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radOrdenCompraActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDevolucion);
        radDevolucion.setText("Devoulución");
        radDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDevolucionActionPerformed(evt);
            }
        });

        jLCliente.setText("Cliente:");

        jLFactura.setText("Factura:");

        jLMotivo.setText("Motivo:");

        txtFactura.setEnabled(false);

        txtCliente.setEnabled(false);

        btnIncorporar.setText("Incorporar");
        btnIncorporar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncorporarActionPerformed(evt);
            }
        });

        txtMotivo.setEnabled(false);
        jScrollPane1.setViewportView(txtMotivo);

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel10.setText("Código:");

        jLabel2.setText("Cantidad:");

        txtCantidad.setEnabled(false);

        cmbTipo.setEditable(true);
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Producto", "Perecedero" }));
        cmbTipo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMotivo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLFactura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIncorporar)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFactura)
                    .addComponent(txtCliente)
                    .addComponent(jScrollPane1))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(radOrdenCompra)
                        .addGap(99, 99, 99)
                        .addComponent(radDevolucion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addGap(0, 119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radDevolucion)
                            .addComponent(radOrdenCompra))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLCliente)))
                                    .addComponent(jLFactura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMotivo)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIncorporar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radOrdenCompraActionPerformed
        mostrarCompra();
        updateState();
    }//GEN-LAST:event_radOrdenCompraActionPerformed

    private void updateState() {
        if (radOrdenCompra.isFocusOwner()) {        
        txtFactura.setEnabled(false);
        txtCliente.setEnabled(false);
        txtMotivo.setEnabled(false);
        }
        else {
        txtFactura.setEnabled(true);
        txtCliente.setEnabled(true);
        txtMotivo.setEnabled(true);
        }
        
        if (radDevolucion.isFocusOwner()) {        
        txtCodigo.setEnabled(false);
        txtCantidad.setEnabled(false);
        cmbTipo.setEnabled(false);
        }
        else {
        txtCodigo.setEnabled(true);
        txtCantidad.setEnabled(true);
        cmbTipo.setEnabled(true);
        }
    }
    
    private void btnIncorporarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncorporarActionPerformed
        try {
            File file = new File("productos.txt");
            if (file.exists()) {
                FileInputStream in = new FileInputStream(file);
                ObjectInputStream entrada = new ObjectInputStream(in);
                productos = (ArrayList<Producto>) entrada.readObject();
                
                entrada.close();
            } else {
                throw new Exception();
            }
        } catch (Exception ex) {
            System.out.println("Error al recuperar el archivo");
        }
        //
        //String codigo = txtCodigoProducto.getText();
        //int cantidad = Integer.parseInt(txtCantidadProducto.getText());
        if (radOrdenCompra.isFocusOwner()) {
            for (Producto p : productos) {
                if (p.getCodigo() == txtCodigo.getText())
                    p.setCantidad(p.getCantidad()+Integer.parseInt(txtCantidad.getText()));
                else if (p.getCodigo() != txtCodigo.getText())
                    JOptionPane.showMessageDialog(null, "El producto no esta registrado.");
            }
        }
        else if (radDevolucion.isFocusOwner()) {
            
        }
    }//GEN-LAST:event_btnIncorporarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void radDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDevolucionActionPerformed
        mostrarCompra();
        updateState();
    }//GEN-LAST:event_radDevolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncorporar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLFactura;
    private javax.swing.JLabel jLMotivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radDevolucion;
    private javax.swing.JRadioButton radOrdenCompra;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextPane txtMotivo;
    // End of variables declaration//GEN-END:variables
}
